Рабочая тетрадь 2

1.2.1 Пример
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.


In [ ]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [ ]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, b, c, d, sep = "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0018769926958858152 0.9938185557398408 0.48549381811002484


1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [ ]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример


In [ ]:
import numpy as np
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример
Отсортировать массив.

In [ ]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
import numpy as np
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.


In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.0249356  0.26249844 0.63491156]
  [0.81596618 0.47308866 0.01321029]
  [0.06352803 0.29939964 0.88286817]]

 [[0.18665317 0.2547376  0.99073625]
  [0.22483542 0.14943909 0.49899753]
  [0.68826046 0.15360709 0.52737049]]

 [[0.68873287 0.49095065 0.98092066]
  [0.37016322 0.39077587 0.53957762]
  [0.99930529 0.56638003 0.3473849 ]]]


1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5 Задание
Создайте массив и отсортируйте его по убыванию

In [ ]:
import numpy as np
Z = np.random.random((10))
print(np.sort(Z)[::-1])

[0.9938053  0.98893492 0.83629845 0.71873068 0.70040703 0.61153056
 0.41262538 0.36327278 0.0984203  0.07448896]


1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
import numpy as np
Z = np.array([[1,2,3],[4,5,6]])

print(Z.shape)
print(Z.size)

(2, 3)
6


2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего). 


In [ ]:
import pandas as pd
import numpy as np

lst = [1,2,3,4,5]
d = {'a' : 1, 'b':2, 'c' : 3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst) 
s2 = pd.Series(d)
s3 = pd.Series(ndarr)

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


2.2.2 Пример 
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).


In [ ]:
import pandas as pd
import numpy as np

s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])

print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример
Создайте новый фрейм данных.


In [ ]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['name'] = ['Jay Jay', 'Siven Bob']
dataframe['age'] = [38,25]
dataframe['driver'] = [True, False]
dataframe

name  age  driver
0    Jay Jay   38    True
1  Siven Bob   25   False

2.2.4 Пример
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv


In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)

dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

2.2.5 Пример
Пронализировать характеристики фрейма данных.

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)


dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)


dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

2.2.7 Пример Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.


In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

dataframe = pd.read_csv(url)


dataframe[dataframe['PClass'] == '1st'].head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

2.3.1 Задание Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [ ]:

import pandas as pd
import numpy as np
  
  

x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 10])
  

p1 = np.sum([(a * a) for a in x])
p2 = np.sum([(b * b) for b in y])
  

p3 = -1 * np.sum([(2 * a*b) for (a, b) in zip(x, y)])
dist = np.sqrt(np.sum(p1 + p2 + p3))
  
print("Series 1:", x)
print("Series 2:", y)
print("Euclidean distance between two series is:", dist)

Series 1: 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series 2: 0     6
1     7
2     8
3     9
4    10
dtype: int64
Euclidean distance between two series is: 11.180339887498949


2.3.2 Задание Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe = pd.read_csv(url)
dataframe.head(5)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0

2.3.3 Задание 
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe = pd.read_csv(url)
dataframe.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe = pd.read_csv(url)
dataframe.iloc[1:4]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

dataframe = pd.read_csv(url)

dataframe[dataframe['Airline'] == 'US'].head(5)


Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
1       US    1558         PHX       CLT          3    15     222      1
15      US     498         DEN       CLT          3    55     179      0
24      US     122         ANC       PHX          3   113     327      1
31      US    1011         EWR       CLT          3   300     111      0
32      US    1983         BOS       CLT          3   300     135      0

3.2.1 Пример Прошкалируйте числовой признак в диапазон между двумя значениями.

In [ ]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2 Пример 
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

standardized


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

3.2.3 Пример Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})

dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd

from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)

dataframe[['sepal_length_cm']] = preprocessing.MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = preprocessing.StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]